services:
  # nginx:
  #   image: nginx:latest
  #   container_name: nginx
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
  #     - ./nginx/html:/usr/share/nginx/html:ro
  #   networks:
  #     - app-network

  frontend:
    container_name: frontend
    build:
      context: ./frontend/
      dockerfile: ./Dockerfile
      args:
        API_URL: 195.133.50.157:8000
    ports:
      - "80:80"
    networks:
      - app-network
    depends_on:
      - backend

  backend:
    container_name: backend
    build:
      context: ./backend/
      dockerfile: ./cmd/Dockerfile
    environment:
      ORIGIN: http://195.133.50.157/, http://webontology.ru, http://localhost:8080
      TZ: Europe/Moscow
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
<<<<<<< HEAD
=======

>>>>>>> 19858e2 (add new layout; update port;)
    ports:
      - "8000:8000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
