events {
    # Настройки событий (можно оставить пустым)
    worker_connections 1024;
}

http {
		include /etc/nginx/mime.types;

    client_body_timeout 60s;
    client_header_timeout 60s;
    send_timeout 60s;

	  server {
	    listen 80;
	    server_name webontology.ru www.webontology.ru;

	    location / {
	        proxy_pass http://frontend:80;
	        proxy_set_header Host $host;
	        proxy_set_header X-Real-IP $remote_addr;
	        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
	        proxy_set_header X-Forwarded-Proto $scheme;
	    }

	    location /api/ {
	        proxy_pass http://backend:3080;
	        proxy_set_header Host $host;
	        proxy_set_header X-Real-IP $remote_addr;
	        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
	        proxy_set_header X-Forwarded-Proto $scheme;
	        proxy_set_header Origin $http_origin;
	    }
		}
}
